stages:          # List of stages for jobs and their order of execution
  - publish

publish-job:
  stage: publish
  image: node
  only: [tags, web]
  script:
    - yarn publish --//registry.npmjs.org/:_authToken=${NPM_TOKEN} --non-interactive