stages:          # List of stages for jobs and their order of execution
  - publish

publish-job:
  stage: publish
  image: node
  only: [tags, web]
  variables:
    NPM_AUTH_TOKEN: ${NPM_TOKEN}
  script:
    - yarn publish --non-interactive