image: node:18

pipelines:
  default:
    - step:
        name: publish
        caches:
          - node
        script:
          - node --version
          - corepack enable
          - npm config set '//registry.npmjs.org/:_authToken' ${NPM_TOKEN} --local
          - yarn publish --non-interactive