version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.5

jobs:
  publish:
    executor: node-executor
    steps:
      - run:
        name: 'publish'
        command: |
          git clone https://gitgud.io/xiaochuan/xiaochuan-source-dev.git
          cd xiaochuan-source-dev
          corepack enable
          npm config set '//registry.npmjs.org/:_authToken' ${NPM_TOKEN} --local
          yarn publish --non-interactive

workflows:
  publish_job:
    jobs:
      - publish
