steps:
  - name: publish
    when:
      - branch: master
      - event: push
      - path: 'package.json'

    image: node:20.18.1
    commands:
      - node --version
      - corepack enable
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN --local
      - yarn publish --non-interactive
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN