steps:
  - name: publish
    when:
      - branch: master
      - event: push

    image: node:20.18.1
    commands:
      # - node --version
      # - corepack enable
      # - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN --local
      # - npm publish
      - curl https://registry.npmjs.org/xiaochuan-source-dev
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN