name: publish

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: node --version
      - run: corepack enable
      - run: yarn
      - run: yarn publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}